/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main1.java
 *
 * Created on Oct 30, 2014, 10:02:54 AM
 */
package uninstallproject;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Dell
 */
public class Main extends javax.swing.JFrame {

    /** Creates new form Main1 */
    private ImageIcon icon = null;
    private Image image = null;
    private CardLayout cardLayout;
    private String path = "C:\\";

    public Main() {
        initComponents();
        setLocationRelativeTo(this);
        jPanel1.setSize(500, 350);
        URL url = getClass().getResource("saleperson1.png");
        image = Toolkit.getDefaultToolkit().getImage(url);
        icon = new ImageIcon(image);
        lblSalePerson.setIcon(icon);

        ImageIcon icon = new ImageIcon(getClass().getResource("icon.png"));
        Image im = icon.getImage();
        setIconImage(im);

        PanelStart pStart = new PanelStart();

        jPanel1.add(pStart, "pStart");



        jButton1.addMouseListener(new MouseEventClickButton("", "", ""));
        jButton2.addMouseListener(new MouseEventClickButton("", "", ""));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackgroud1 = new uninstallproject.PanelBackgroud();
        lblSalePerson = new javax.swing.JLabel();
        lblSupport = new javax.swing.JLabel();
        lblNameCpn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblNameCpn1 = new javax.swing.JLabel();
        lblNameCpn2 = new javax.swing.JLabel();
        lblNameCpn3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gỡ bỏ phần mềm HKT");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 570, 400));
        setResizable(false);

        panelBackgroud1.setLayout(null);
        panelBackgroud1.add(lblSalePerson);
        lblSalePerson.setBounds(10, 70, 100, 140);

        lblSupport.setText("<html><b>0437 925 193<br>0904 894 728<br></b></html>");
        lblSupport.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelBackgroud1.add(lblSupport);
        lblSupport.setBounds(20, 250, 80, 40);

        lblNameCpn.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblNameCpn.setForeground(new java.awt.Color(149, 55, 53));
        lblNameCpn.setText("Tư vấn hỗ trợ");
        lblNameCpn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelBackgroud1.add(lblNameCpn);
        lblNameCpn.setBounds(10, 230, 100, 20);

        jPanel2.setBackground(new java.awt.Color(226, 237, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(435, 302));
        jPanel2.setMinimumSize(new java.awt.Dimension(435, 302));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uninstallproject/iconOk1.png"))); // NOI18N
        jButton2.setText("Gỡ phần mềm");
        jButton2.setBorderPainted(false);
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2.setPreferredSize(new java.awt.Dimension(135, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uninstallproject/iconBackExit.png"))); // NOI18N
        jButton1.setText("Hủy");
        jButton1.setBorderPainted(false);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(226, 237, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(435, 302));
        jPanel1.setMinimumSize(new java.awt.Dimension(435, 302));
        jPanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelBackgroud1.add(jPanel2);
        jPanel2.setBounds(120, 55, 440, 340);

        lblNameCpn1.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblNameCpn1.setForeground(new java.awt.Color(149, 55, 53));
        lblNameCpn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameCpn1.setText("Version 4.0");
        panelBackgroud1.add(lblNameCpn1);
        lblNameCpn1.setBounds(10, 340, 100, 40);

        lblNameCpn2.setFont(new java.awt.Font("Tahoma", 1, 16));
        lblNameCpn2.setForeground(new java.awt.Color(255, 255, 255));
        lblNameCpn2.setText("Công ty CP Tư vấn Quản trị HKT");
        lblNameCpn2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelBackgroud1.add(lblNameCpn2);
        lblNameCpn2.setBounds(290, 20, 260, 20);

        lblNameCpn3.setFont(new java.awt.Font("Tahoma", 1, 15));
        lblNameCpn3.setForeground(new java.awt.Color(149, 55, 53));
        lblNameCpn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameCpn3.setText("HKT Software");
        lblNameCpn3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelBackgroud1.add(lblNameCpn3);
        lblNameCpn3.setBounds(10, 20, 120, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uninstallproject/Logo HKT.png"))); // NOI18N
        panelBackgroud1.add(jLabel1);
        jLabel1.setBounds(10, 290, 90, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackgroud1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackgroud1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String getWin() {
        try {
            File f = new File(readData() + "\\server\\bin\\Win.vbs");
            Process p = Runtime.getRuntime().exec("cscript //NoLogo " + f.getPath());
            String sn = "";
            BufferedReader input = new BufferedReader(new InputStreamReader(p.getInputStream()));
            String line;
            while ((line = input.readLine()) != null) {
                sn = sn + line;
            }
            input.close();
            if (sn.equals("64")) {
                return "HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\HKT Software 4.0";
            } else {
                return "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\HKT Software 4.0";
            }
        } catch (Exception e) {
            return "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\HKT Software 4.0";
        }

    }
private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
        File f11 = new File(defaultDirectory() + "\\Desktop\\HKT Software 4.0.lnk");
        f11.delete();
        FileUtils.deleteDir(defaultDirectory()+"\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\HKT_Software_4.0");
        File file = new File(readData() + "/server/Uninstall.vbs");

        String path = file.getPath().replace("%20", " ");
        Runtime.getRuntime().exec("cscript //NoLogo " + "\"" + path);
        Thread.sleep(1500);

        File file22 = File.createTempFile("realhowto", ".bat");
        FileWriter fw12 = new java.io.FileWriter(file22);
        String vbs111 = "reg delete \"" + getWin() + "\" /f";
        fw12.write(vbs111);
        fw12.close();


        File file1 = File.createTempFile("realhowto", ".vbs");

        FileWriter fw1 = new java.io.FileWriter(file1);
        File file3 = new File(readData());
        String vbs11 = "Set WshShell = CreateObject(\"WScript.Shell\") \n"
                + "WshShell.Run chr(34) & " + "\"" + file22.getPath() + "\"\n"
                + "Set WshShell = Nothing \n"
                + "CreateObject(\"Scripting.FileSystemObject\")"
                + ".DeleteFolder " + "\"" + file3.getPath() + "\"";

        fw1.write(vbs11);
        fw1.close();
        Runtime.getRuntime().exec("cscript //NoLogo " + file1.getPath());
        File f1 = new File(readData());
        f1.delete();
        File f = getFile("Database", "setup");
        f.delete();

        System.exit(0);
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
}//GEN-LAST:event_jButton1ActionPerformed
    private String readData() {
        try {
            FileInputStream fi = new FileInputStream(getFile("Database", "setup").getAbsoluteFile());
            ObjectInputStream of = new ObjectInputStream(fi);
            String str = of.readObject().toString();
            of.close();
            return str;
        } catch (Exception e) {
            return "";

        }

    }

    public File getFile(String module, String nameFile) {
        String directory = defaultDirectory() + File.separator
                + "HKTSoftwareEnterpriseManager" + File.separator + module;
        if (!new File(directory).exists()) {
            new File(directory).mkdirs();
        }
        String path = directory + File.separator + nameFile;;
        return new File(path);
    }

    private String defaultDirectory() {
        String OS = System.getProperty("os.name").toUpperCase();
        if (OS.contains("WIN")) {
            return System.getProperty("user.home");
        } else if (OS.contains("MAC")) {
            return System.getProperty("user.home") + "/Library/Application "
                    + "Support";
        } else if (OS.contains("NUX")) {
            return System.getProperty("user.home");
        }
        return System.getProperty("user.dir");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNameCpn;
    private javax.swing.JLabel lblNameCpn1;
    private javax.swing.JLabel lblNameCpn2;
    private javax.swing.JLabel lblNameCpn3;
    private javax.swing.JLabel lblSalePerson;
    private javax.swing.JLabel lblSupport;
    private uninstallproject.PanelBackgroud panelBackgroud1;
    // End of variables declaration//GEN-END:variables
}
